name: RASPlant
description: Um aplicativo para identificar PANCS.

publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  camera: ^0.5.8+11
  path_provider: ^1.6.24
  path: ^1.7.0
  esys_flutter_share: ^1.0.2
  fluttericon: ^1.0.7
  footer: ^0.0.3
  percent_indicator: ^2.1.8
  carousel_pro: ^1.0.0
  sqflite: 
  tflite: ^1.1.1
  image:
  modal_progress_hud: ^0.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:


  uses-material-design: true

  assets:
    - assets/Araruta/
    - assets/Beldroegão/
    - assets/Capiçoba/
    - assets/Capuchinha/
    - assets/Caruru/
    - assets/Ora-pro-nóbis/
    - assets/Peixinho/
    - assets/Picão-preto/
    - assets/Serralha/
    - assets/Taioba/
    - assets/Urtiga/
    - assets/model.tflite
    - assets/labels.txt

  
