name: identificador_plantas
description: Um aplicativo para identificar PANCS.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  camera: ^0.5.8+11
  path_provider: ^1.6.24
  path: ^1.7.0
  esys_flutter_share: ^1.0.2
  fluttericon: ^1.0.7
  footer: ^0.0.3
  percent_indicator: ^2.1.8
  carousel_pro: ^1.0.0
  sqflite:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - assets/Images/
  
